package org.datatypeproject.impl;

enum WhiteSpace {
  FORBID_WHITESPACE,
  PRESERVE_WHITESPACE,
  PRESERVE_AND_CONVERT_WHITESPACE,
  NORMALIZE_WHITESPACE,
  NORMALIZE_AND_CONVERT_WHITESPACE,
  REMOVE_WHITESPACE,
}
