package org.typefactory.assertions;

import java.util.Objects;
import org.assertj.core.api.AbstractComparableAssert;
import org.typefactory.LongType;
import org.typefactory.Type;

/**
 * Abstract base class for {@link LongType} specific assertions - Generated by CustomAssertionGenerator.
 */
@SuppressWarnings("java:S119") // Generic parameter naming
public abstract class AbstractLongTypeAssert<SELF extends AbstractLongTypeAssert<SELF, ACTUAL>, ACTUAL extends LongType> extends AbstractComparableAssert<SELF, ACTUAL> {

  /**
   * Creates a new <code>{@link AbstractLongTypeAssert}</code> to make assertions on actual LongType.
   * @param actual the LongType we want to make assertions on.
   */
  protected AbstractLongTypeAssert(ACTUAL actual, Class<SELF> selfType) {
    super(actual, selfType);
  }

  private String simpleClassNameOfActual() {
    return actual == null ? "custom type extending StringType" : actual.getClass().getSimpleName();
  }

  private String valueOfActual() {
    return Type.isNull(actual) ? "null" : Objects.toString(actual.value());
  }

  public SELF hasValue(long expected) {
    isNotNull();
    if (!Objects.equals(actual.value(), expected)) {
      throw failureWithActualExpected(
          valueOfActual(), expected,
          "Expected %s value to be <%s> but was <%s>",
          simpleClassNameOfActual(), expected, valueOfActual());
    }
    return myself;
  }

  public SELF hasValue(Long expected) {
    isNotNull();
    if (expected == null) {
      if (Type.isNull(actual)) {
        return myself;
      } else {
        throw failure("Expected %s to be null but was <%s>", simpleClassNameOfActual(), valueOfActual());
      }
    }
    return hasValue(expected.longValue());
  }

  public SELF hasNullValue(Long expected) {
    if (expected == null) {
      if (Type.isNull(actual)) {
        return myself;
      } else {
        throw failure("Expected %s to be null but was <%s>", simpleClassNameOfActual(), valueOfActual());
      }
    }
    return hasValue(expected.longValue());
  }

  @Override
  public void isNull() {
    if (Type.isNull(actual)) {
      return;
    }
    throw failure("Expected %s value to be null but was <%s>", simpleClassNameOfActual(), valueOfActual());
  }

  @Override
  public SELF isNotNull() {
    if (Type.isNull(actual)) {
      throw failure("Expected %s value to be non-null but was null", simpleClassNameOfActual());
    }
    return myself;
  }
}
