package org.typefactory.assertions;

import org.assertj.core.util.CheckReturnValue;
import org.typefactory.CharSequenceType;
import org.typefactory.StringType;

/**
 * <p>{@link StringType} specific assertions - Generated by CustomAssertionGenerator.</p>
 *
 * <p>Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractStringTypeAssert} instead.</p>
 */
public class CharSequenceTypeAssert extends AbstractCharSequenceTypeAssert<CharSequenceTypeAssert, CharSequenceType<?>> {

  /**
   * Creates a new <code>{@link CharSequenceTypeAssert}</code> to make assertions on actual StringType.
   * @param actual the StringType we want to make assertions on.
   */
  public CharSequenceTypeAssert(final CharSequenceType<?> actual) {
    super(actual, CharSequenceTypeAssert.class);
  }

  /**
   * An entry point for StringTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myStringType)</code> and get specific assertion with code completion.
   * @param actual the StringType we want to make assertions on.
   * @return a new <code>{@link CharSequenceTypeAssert}</code>
   */
  @CheckReturnValue
  public static <T extends CharSequenceType<T>> CharSequenceTypeAssert assertThat(T actual) {
    return new CharSequenceTypeAssert(actual);
  }
}
