package org.typefactory.assertions;

import org.assertj.core.util.CheckReturnValue;
import org.typefactory.ShortType;

/**
 * <p>{@link ShortType} specific assertions - Generated by CustomAssertionGenerator.</p>
 *
 * <p>Although this class is not final to allow Soft assertions proxy, if you wish to extend it,
 * extend {@link AbstractShortTypeAssert} instead.</p>
 */
public class ShortTypeAssert extends AbstractShortTypeAssert<ShortTypeAssert, ShortType> {

  /**
   * Creates a new <code>{@link ShortTypeAssert}</code> to make assertions on actual ShortType.
   * @param actual the ShortType we want to make assertions on.
   */
  public ShortTypeAssert(ShortType actual) {
    super(actual, ShortTypeAssert.class);
  }

  /**
   * An entry point for ShortTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myShortType)</code> and get specific assertion with code completion.
   * @param actual the ShortType we want to make assertions on.
   * @return a new <code>{@link ShortTypeAssert}</code>
   */
  @CheckReturnValue
  public static ShortTypeAssert assertThat(ShortType actual) {
    return new ShortTypeAssert(actual);
  }
}
