package org.typefactory.assertions;

import org.assertj.core.util.CheckReturnValue;
import org.typefactory.StringType;

/**
 * {@link StringType} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractStringTypeAssert} instead.
 */
public class StringTypeAssert extends AbstractStringTypeAssert<StringTypeAssert, StringType> {

  /**
   * Creates a new <code>{@link StringTypeAssert}</code> to make assertions on actual StringType.
   * @param actual the StringType we want to make assertions on.
   */
  public StringTypeAssert(StringType actual) {
    super(actual, StringTypeAssert.class);
  }

  /**
   * An entry point for StringTypeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myStringType)</code> and get specific assertion with code completion.
   * @param actual the StringType we want to make assertions on.
   * @return a new <code>{@link StringTypeAssert}</code>
   */
  @CheckReturnValue
  public static StringTypeAssert assertThat(StringType actual) {
    return new StringTypeAssert(actual);
  }
}
