package org.typefactory.assertions;

import org.assertj.core.util.CheckReturnValue;
import org.typefactory.Subset;

/**
 * {@link Subset} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractSubsetAssert} instead.
 */
public class SubsetAssert extends AbstractSubsetAssert<SubsetAssert, Subset> {

  /**
   * Creates a new <code>{@link SubsetAssert}</code> to make assertions on actual Subset.
   * @param actual the Subset we want to make assertions on.
   */
  public SubsetAssert(Subset actual) {
    super(actual, SubsetAssert.class);
  }

  /**
   * An entry point for SubsetAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(mySubset)</code> and get specific assertion with code completion.
   * @param actual the Subset we want to make assertions on.
   * @return a new <code>{@link SubsetAssert}</code>
   */
  @CheckReturnValue
  public static SubsetAssert assertThat(Subset actual) {
    return new SubsetAssert(actual);
  }
}
